# Data Cleaning

## Objective

Prepare the raw dataset for feature engineering by applying reproducible cleaning steps while keeping the raw dataset unchanged.

In [32]:
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [34]:
DATA_PATH = Path("../data/raw/laptop_price - dataset.csv")

df = pd.read_csv(DATA_PATH)

df.head()

,Company,Product,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg),Price (Euro)
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [35]:
df_clean = df.copy()

df_clean.head()

,Company,Product,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg),Price (Euro)
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [36]:
df_clean.shape

(1275, 15)

In [37]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Company              1275 non-null   str
 1   Product              1275 non-null   str
 2   TypeName             1275 non-null   str
 3   Inches               1275 non-null   float64
 4   ScreenResolution     1275 non-null   str
 5   CPU_Company          1275 non-null   str
 6   CPU_Type             1275 non-null   str
 7   CPU_Frequency (GHz)  1275 non-null   float64
 8   RAM (GB)             1275 non-null   int64
 9   Memory               1275 non-null   str
 10  GPU_Company          1275 non-null   str
 11  GPU_Type             1275 non-null   str
 12  OpSys                1275 non-null   str
 13  Weight (kg)          1275 non-null   float64
 14  Price (Euro)         1275 non-null   float64
dtypes: float64(4), int64(1), str(10)
memory usage: 149.5 KB

In [38]:
missing_values = df_clean.isnull().sum()

missing_values

Company                0
Product                0
TypeName               0
Inches                 0
ScreenResolution       0
CPU_Company            0
CPU_Type               0
CPU_Frequency (GHz)    0
RAM (GB)               0
Memory                 0
GPU_Company            0
GPU_Type               0
OpSys                  0
Weight (kg)            0
Price (Euro)           0
dtype: int64

In [39]:
missing_report = pd.DataFrame({
    "Missing Values": df_clean.isnull().sum(),
    "Missing Percentage": (
        df_clean.isnull().mean() * 100
    ).round(2)
})

missing_report

                     Missing Values  Missing Percentage
Company                           0                 0.0
Product                           0                 0.0
TypeName                          0                 0.0
Inches                            0                 0.0
ScreenResolution                  0                 0.0
CPU_Company                       0                 0.0
CPU_Type                          0                 0.0
CPU_Frequency (GHz)               0                 0.0
RAM (GB)                          0                 0.0
Memory                            0                 0.0
GPU_Company                       0                 0.0
GPU_Type                          0                 0.0
OpSys                             0                 0.0
Weight (kg)                       0                 0.0
Price (Euro)                      0                 0.0

In [40]:
duplicate_count = df_clean.duplicated().sum()

duplicate_count

np.int64(0)

In [41]:
duplicate_percentage = round(
    duplicate_count / len(df_clean) * 100,
    2
)

print(f"Duplicate Rows: {duplicate_count}")
print(f"Duplicate Percentage: {duplicate_percentage}%")

Duplicate Rows: 0
Duplicate Percentage: 0.0%

In [42]:
column_mapping = {
    "Company": "company",
    "Product": "product",
    "TypeName": "type_name",
    "Inches": "inches",
    "ScreenResolution": "screen_resolution",
    "CPU_Company": "cpu_company",
    "CPU_Type": "cpu_type",
    "CPU_Frequency (GHz)": "cpu_frequency",
    "RAM (GB)": "ram",
    "Memory": "memory",
    "GPU_Company": "gpu_company",
    "GPU_Type": "gpu_type",
    "OpSys": "operating_system",
    "Weight (kg)": "weight",
    "Price (Euro)": "price"
}

In [43]:
column_mapping

{'Company': 'company',
 'Product': 'product',
 'TypeName': 'type_name',
 'Inches': 'inches',
 'ScreenResolution': 'screen_resolution',
 'CPU_Company': 'cpu_company',
 'CPU_Type': 'cpu_type',
 'CPU_Frequency (GHz)': 'cpu_frequency',
 'RAM (GB)': 'ram',
 'Memory': 'memory',
 'GPU_Company': 'gpu_company',
 'GPU_Type': 'gpu_type',
 'OpSys': 'operating_system',
 'Weight (kg)': 'weight',
 'Price (Euro)': 'price'}

In [44]:
df_clean = df_clean.rename(columns=column_mapping)

df_clean.head()

,company,product,type_name,inches,screen_resolution,cpu_company,cpu_type,cpu_frequency,ram,memory,gpu_company,gpu_type,operating_system,weight,price
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [45]:
df_clean.columns

Index(['company', 'product', 'type_name', 'inches', 'screen_resolution',
       'cpu_company', 'cpu_type', 'cpu_frequency', 'ram', 'memory',
       'gpu_company', 'gpu_type', 'operating_system', 'weight', 'price'],
      dtype='str')

In [46]:
df_clean.shape

(1275, 15)

In [47]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   company            1275 non-null   str
 1   product            1275 non-null   str
 2   type_name          1275 non-null   str
 3   inches             1275 non-null   float64
 4   screen_resolution  1275 non-null   str
 5   cpu_company        1275 non-null   str
 6   cpu_type           1275 non-null   str
 7   cpu_frequency      1275 non-null   float64
 8   ram                1275 non-null   int64
 9   memory             1275 non-null   str
 10  gpu_company        1275 non-null   str
 11  gpu_type           1275 non-null   str
 12  operating_system   1275 non-null   str
 13  weight             1275 non-null   float64
 14  price              1275 non-null   float64
dtypes: float64(4), int64(1), str(10)
memory usage: 149.5 KB

### Column Standardization Summary

Column names were standardized using snake_case naming convention.

Special characters, spaces, units and inconsistent naming styles were removed to improve readability and maintainability.

In [48]:
df_clean.dtypes

company                  str
product                  str
type_name                str
inches               float64
screen_resolution        str
cpu_company              str
cpu_type                 str
cpu_frequency        float64
ram                    int64
memory                   str
gpu_company              str
gpu_type                 str
operating_system         str
weight               float64
price                float64
dtype: object

In [49]:
dtype_report = pd.DataFrame({
    "Column": df_clean.columns,
    "Data Type": df_clean.dtypes.values
})

dtype_report

               Column Data Type
0             company       str
1             product       str
2           type_name       str
3              inches   float64
4   screen_resolution       str
5         cpu_company       str
6            cpu_type       str
7       cpu_frequency   float64
8                 ram     int64
9              memory       str
10        gpu_company       str
11           gpu_type       str
12   operating_system       str
13             weight   float64
14              price   float64

In [50]:
print("Shape:", df_clean.shape)
print()

print("Columns:")
print(df_clean.columns.tolist())

Shape: (1275, 15)

Columns:
['company', 'product', 'type_name', 'inches', 'screen_resolution', 'cpu_company', 'cpu_type', 'cpu_frequency', 'ram', 'memory', 'gpu_company', 'gpu_type', 'operating_system', 'weight', 'price']

In [51]:
expected_columns = [
    "company",
    "product",
    "type_name",
    "inches",
    "screen_resolution",
    "cpu_company",
    "cpu_type",
    "cpu_frequency",
    "ram",
    "memory",
    "gpu_company",
    "gpu_type",
    "operating_system",
    "weight",
    "price"
]

In [52]:
set(df_clean.columns) == set(expected_columns)

True

In [53]:
df_clean.head()

,company,product,type_name,inches,screen_resolution,cpu_company,cpu_type,cpu_frequency,ram,memory,gpu_company,gpu_type,operating_system,weight,price
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [54]:
PROCESSED_DATA_PATH = Path("../data/processed/laptop_cleaned.csv")

df_clean.to_csv(PROCESSED_DATA_PATH, index=False)

print(f"Processed dataset saved to:\n{PROCESSED_DATA_PATH}")

Processed dataset saved to:
..\data\processed\laptop_cleaned.csv

In [55]:
df_processed = pd.read_csv(PROCESSED_DATA_PATH)

df_processed.head()

,company,product,type_name,inches,screen_resolution,cpu_company,cpu_type,cpu_frequency,ram,memory,gpu_company,gpu_type,operating_system,weight,price
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [56]:
df_processed.shape

(1275, 15)

# Data Cleaning Summary

The dataset has been successfully cleaned and validated.

### Completed Tasks

- Created a working copy of the dataset
- Verified missing values
- Verified duplicate rows
- Standardized column names using `snake_case`
- Validated data types
- Validated dataset structure
- Saved the cleaned dataset to `data/processed/laptop_cleaned.csv`

The cleaned dataset is now ready for the Feature Engineering stage.

In [57]:
# preprocessing.py Test
from src.data_loader import PROJECT_ROOT
from src.data_loader import RAW_DATA_DIR

print(PROJECT_ROOT)
print(RAW_DATA_DIR)

E:\laptop-price-prediction
E:\laptop-price-prediction\data\raw

In [59]:
from src.data_loader import load_data
from src.preprocessing import clean_data

df_test = load_data("laptop_price - dataset.csv")
df_test_clean = clean_data(df_test)

df_test_clean.columns

Index(['company', 'product', 'type_name', 'inches', 'screen_resolution',
       'cpu_company', 'cpu_type', 'cpu_frequency', 'ram', 'memory',
       'gpu_company', 'gpu_type', 'operating_system', 'weight', 'price'],
      dtype='str')