In [1]:
import warnings
warnings.filterwarnings("ignore")

import sys
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [2]:
from src.data_loader import load_data

DATA_PATH = Path("../data/processed/laptop_cleaned.csv")

df = pd.read_csv(DATA_PATH)

df.head()

,company,product,type_name,inches,screen_resolution,cpu_company,cpu_type,cpu_frequency,ram,memory,gpu_company,gpu_type,operating_system,weight,price
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   company            1275 non-null   str
 1   product            1275 non-null   str
 2   type_name          1275 non-null   str
 3   inches             1275 non-null   float64
 4   screen_resolution  1275 non-null   str
 5   cpu_company        1275 non-null   str
 6   cpu_type           1275 non-null   str
 7   cpu_frequency      1275 non-null   float64
 8   ram                1275 non-null   int64
 9   memory             1275 non-null   str
 10  gpu_company        1275 non-null   str
 11  gpu_type           1275 non-null   str
 12  operating_system   1275 non-null   str
 13  weight             1275 non-null   float64
 14  price              1275 non-null   float64
dtypes: float64(4), int64(1), str(10)
memory usage: 149.5 KB

In [4]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
company,1275,19,Dell,291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product,1275,618,XPS 13,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
type_name,1275,6,Notebook,707,NaN,NaN,NaN,NaN,NaN,NaN,NaN
inches,1275.0,NaN,NaN,NaN,15.022902,1.42947,10.1,14.0,15.6,15.6,18.4
screen_resolution,1275,40,Full HD 1920x1080,505,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpu_company,1275,3,Intel,1214,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpu_type,1275,93,Core i5 7200U,193,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpu_frequency,1275.0,NaN,NaN,NaN,2.30298,0.503846,0.9,2.0,2.5,2.7,3.6
ram,1275.0,NaN,NaN,NaN,8.440784,5.097809,2.0,4.0,8.0,8.0,64.0
memory,1275,39,256GB SSD,412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gpu_company,1275,4,Intel,704,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gpu_type,1275,106,HD Graphics 620,280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
operating_system,1275,9,Windows 10,1048,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weight,1275.0,NaN,NaN,NaN,2.040525,0.669196,0.69,1.5,2.04,2.31,4.7
price,1275.0,NaN,NaN,NaN,1134.969059,700.752504,174.0,609.0,989.0,1496.5,6099.0

In [5]:
feature_plan = pd.DataFrame({
    "Feature": df.columns,
    "Current Type": df.dtypes.astype(str).values,
    "Need Engineering": "",
    "New Features": "",
    "Notes": ""
})

feature_plan

              Feature Current Type Need Engineering New Features Notes
0             company          str
1             product          str
2           type_name          str
3              inches      float64
4   screen_resolution          str
5         cpu_company          str
6            cpu_type          str
7       cpu_frequency      float64
8                 ram        int64
9              memory          str
10        gpu_company          str
11           gpu_type          str
12   operating_system          str
13             weight      float64
14              price      float64

In [6]:
feature_plan["Need Engineering"] = [
    "No",
    "Yes",
    "No",
    "No",
    "Yes",
    "No",
    "Yes",
    "No",
    "No",
    "Yes",
    "No",
    "Yes",
    "No",
    "No",
    "Target"
]

feature_plan["New Features"] = [
    "-",
    "Product Family",
    "-",
    "-",
    "Resolution, IPS, Touchscreen",
    "-",
    "CPU Family",
    "-",
    "-",
    "SSD, HDD, Flash, Hybrid",
    "-",
    "GPU Family",
    "-",
    "-",
    "-"
]

feature_plan["Notes"] = [
    "Encode later",
    "High Cardinality",
    "Encode later",
    "Keep",
    "Extract useful information",
    "Encode later",
    "Simplify CPU names",
    "Keep",
    "Keep",
    "Split memory information",
    "Encode later",
    "Simplify GPU names",
    "Encode later",
    "Keep",
    "Target variable"
]

feature_plan

,Feature,Current Type,Need Engineering,New Features,Notes
0,company,str,No,-,Encode later
1,product,str,Yes,Product Family,High Cardinality
2,type_name,str,No,-,Encode later
3,inches,float64,No,-,Keep
4,screen_resolution,str,Yes,"Resolution, IPS, Touchscreen",Extract useful information
5,cpu_company,str,No,-,Encode later
6,cpu_type,str,Yes,CPU Family,Simplify CPU names
7,cpu_frequency,float64,No,-,Keep
8,ram,int64,No,-,Keep
9,memory,str,Yes,"SSD, HDD, Flash, Hybrid",Split memory information
10,gpu_company,str,No,-,Encode later
11,gpu_type,str,Yes,GPU Family,Simplify GPU names
12,operating_system,str,No,-,Encode later
13,weight,float64,No,-,Keep
14,price,float64,Target,-,Target variable

In [7]:
df["memory"].value_counts().head(20)

memory
256GB SSD               412
1TB HDD                 215
500GB HDD               124
512GB SSD               114
128GB SSD +  1TB HDD     94
128GB SSD                74
256GB SSD +  1TB HDD     73
32GB Flash Storage       36
2TB HDD                  16
512GB SSD +  1TB HDD     14
1TB SSD                  14
64GB Flash Storage       13
256GB SSD +  2TB HDD     10
256GB Flash Storage       8
1.0TB Hybrid              7
16GB Flash Storage        7
32GB SSD                  6
180GB SSD                 5
128GB Flash Storage       4
16GB SSD                  3
Name: count, dtype: int64

In [8]:
df["memory"].sample(10, random_state=42)

1179               500GB HDD
342                  1TB HDD
649                256GB SSD
772                128GB SSD
803                256GB SSD
358                  2TB HDD
44                   1TB HDD
231                500GB HDD
618     256GB SSD +  1TB HDD
43                 256GB SSD
Name: memory, dtype: str

## Memory Column Analysis

In [9]:
sorted(df["memory"].unique())

['1.0TB HDD',
 '1.0TB Hybrid',
 '128GB Flash Storage',
 '128GB HDD',
 '128GB SSD',
 '128GB SSD +  1TB HDD',
 '128GB SSD +  2TB HDD',
 '16GB Flash Storage',
 '16GB SSD',
 '180GB SSD',
 '1TB HDD',
 '1TB HDD +  1TB HDD',
 '1TB SSD',
 '1TB SSD +  1TB HDD',
 '240GB SSD',
 '256GB Flash Storage',
 '256GB SSD',
 '256GB SSD +  1.0TB Hybrid',
 '256GB SSD +  1TB HDD',
 '256GB SSD +  256GB SSD',
 '256GB SSD +  2TB HDD',
 '256GB SSD +  500GB HDD',
 '2TB HDD',
 '32GB Flash Storage',
 '32GB HDD',
 '32GB SSD',
 '500GB HDD',
 '508GB Hybrid',
 '512GB Flash Storage',
 '512GB SSD',
 '512GB SSD +  1.0TB Hybrid',
 '512GB SSD +  1TB HDD',
 '512GB SSD +  256GB SSD',
 '512GB SSD +  2TB HDD',
 '512GB SSD +  512GB SSD',
 '64GB Flash Storage',
 '64GB Flash Storage +  1TB HDD',
 '64GB SSD',
 '8GB SSD']

In [10]:
# Check for TB
df[df["memory"].str.contains("TB")]["memory"].unique()

<StringArray>
[                      '1TB HDD',          '128GB SSD +  1TB HDD',
          '256GB SSD +  1TB HDD',          '256GB SSD +  2TB HDD',
                       '2TB HDD',                  '1.0TB Hybrid',
          '512GB SSD +  1TB HDD',                       '1TB SSD',
          '128GB SSD +  2TB HDD',          '512GB SSD +  2TB HDD',
 '64GB Flash Storage +  1TB HDD',            '1TB HDD +  1TB HDD',
            '1TB SSD +  1TB HDD',                     '1.0TB HDD',
     '512GB SSD +  1.0TB Hybrid',     '256GB SSD +  1.0TB Hybrid']
Length: 16, dtype: str

In [11]:
# Checking for Flash Storage
df[df["memory"].str.contains("Flash")]["memory"].unique()

<StringArray>
[          '128GB Flash Storage',           '256GB Flash Storage',
            '32GB Flash Storage',            '64GB Flash Storage',
            '16GB Flash Storage', '64GB Flash Storage +  1TB HDD',
           '512GB Flash Storage']
Length: 7, dtype: str

In [12]:
# Check for Hybrid existence
df[df["memory"].str.contains("Hybrid")]["memory"].unique()

<StringArray>
[             '1.0TB Hybrid',              '508GB Hybrid',
 '512GB SSD +  1.0TB Hybrid', '256GB SSD +  1.0TB Hybrid']
Length: 4, dtype: str

In [13]:
# Checking for the presence of two memories
df[df["memory"].str.contains("\+")]["memory"].unique()

<StringArray>
[         '128GB SSD +  1TB HDD',        '256GB SSD +  256GB SSD',
          '256GB SSD +  1TB HDD',          '256GB SSD +  2TB HDD',
          '512GB SSD +  1TB HDD',        '256GB SSD +  500GB HDD',
          '128GB SSD +  2TB HDD',        '512GB SSD +  512GB SSD',
        '512GB SSD +  256GB SSD',          '512GB SSD +  2TB HDD',
 '64GB Flash Storage +  1TB HDD',            '1TB HDD +  1TB HDD',
            '1TB SSD +  1TB HDD',     '512GB SSD +  1.0TB Hybrid',
     '256GB SSD +  1.0TB Hybrid']
Length: 15, dtype: str

In [14]:
memory_examples = df["memory"].sample(10, random_state=42)

memory_examples

1179               500GB HDD
342                  1TB HDD
649                256GB SSD
772                128GB SSD
803                256GB SSD
358                  2TB HDD
44                   1TB HDD
231                500GB HDD
618     256GB SSD +  1TB HDD
43                 256GB SSD
Name: memory, dtype: str

In [15]:
for value in memory_examples:
    print(value)

500GB HDD
1TB HDD
256GB SSD
128GB SSD
256GB SSD
2TB HDD
1TB HDD
500GB HDD
256GB SSD +  1TB HDD
256GB SSD

In [16]:
for value in memory_examples:
    print(value.split("+"))

['500GB HDD']
['1TB HDD']
['256GB SSD']
['128GB SSD']
['256GB SSD']
['2TB HDD']
['1TB HDD']
['500GB HDD']
['256GB SSD ', '  1TB HDD']
['256GB SSD']

In [17]:
sample = "256GB SSD + 1TB HDD"

parts = sample.split("+")

parts

['256GB SSD ', ' 1TB HDD']

In [18]:
for part in parts:
    print(part.strip())

256GB SSD
1TB HDD

In [19]:
sample = "256GB SSD + 1TB HDD"

parts = sample.split("+")
parts = [part.strip() for part in parts]

parts

['256GB SSD', '1TB HDD']

In [20]:
for part in parts:
    capacity = part.split()[0]
    print(capacity)

256GB
1TB

In [21]:
for part in parts:

    capacity = part.split()[0]

    if "TB" in capacity:
        capacity = float(capacity.replace("TB", "")) * 1024

    else:
        capacity = float(capacity.replace("GB", ""))

    print(capacity)

256.0
1024.0

In [22]:
def extract_capacity(text):

    capacity = text.split()[0]

    if "TB" in capacity:
        return float(capacity.replace("TB", "")) * 1024

    return float(capacity.replace("GB", ""))

In [23]:
extract_capacity("256GB SSD")

256.0

In [24]:
extract_capacity("1TB HDD")

1024.0

In [25]:
extract_capacity("1.0TB Hybrid")

1024.0

In [26]:
extract_capacity("64GB Flash Storage")

64.0

In [27]:
# SSD detection function
def extract_ssd(text):

    parts = [part.strip() for part in text.split("+")]

    ssd = 0

    for part in parts:

        if "SSD" in part:
            ssd += extract_capacity(part)

    return ssd

In [28]:
extract_ssd("256GB SSD + 1TB HDD")

256.0

In [29]:
extract_ssd("512GB SSD + 512GB SSD")

1024.0

In [30]:
extract_ssd("1TB HDD")

0

In [31]:
extract_ssd("64GB Flash Storage")

0

In [32]:
df["ssd"] = df["memory"].apply(extract_ssd)

In [33]:
df[["memory", "ssd"]].head(10)

                memory    ssd
0            128GB SSD  128.0
1  128GB Flash Storage    0.0
2            256GB SSD  256.0
3            512GB SSD  512.0
4            256GB SSD  256.0
5            500GB HDD    0.0
6  256GB Flash Storage    0.0
7  256GB Flash Storage    0.0
8            512GB SSD  512.0
9            256GB SSD  256.0

In [ ]:
(df["ssd"] > 0).sum()
# Count the number of SSDs

np.int64(837)

In [35]:
df[df["ssd"] > 0][["memory", "ssd"]].sample(10, random_state=42)

                    memory    ssd
312   256GB SSD +  1TB HDD  256.0
1243             512GB SSD  512.0
119              256GB SSD  256.0
105              256GB SSD  256.0
600              256GB SSD  256.0
572              256GB SSD  256.0
55               256GB SSD  256.0
427              256GB SSD  256.0
679              256GB SSD  256.0
533               32GB SSD   32.0

In [ ]:
df["ssd"].max()
# Maximum SSD

np.float64(1024.0)

In [37]:
sorted(df["ssd"].unique())

[np.float64(0.0),
 np.float64(8.0),
 np.float64(16.0),
 np.float64(32.0),
 np.float64(64.0),
 np.float64(128.0),
 np.float64(180.0),
 np.float64(240.0),
 np.float64(256.0),
 np.float64(512.0),
 np.float64(768.0),
 np.float64(1024.0)]

In [38]:
df[df["ssd"] == 180][["memory", "ssd"]]

         memory    ssd
477   180GB SSD  180.0
495   180GB SSD  180.0
753   180GB SSD  180.0
873   180GB SSD  180.0
1087  180GB SSD  180.0

In [39]:
df[df["ssd"] == 240][["memory", "ssd"]]

        memory    ssd
911  240GB SSD  240.0

In [ ]:
def extract_hdd(text):

    parts = [part.strip() for part in text.split("+")]

    hdd = 0

    for part in parts:

        if "HDD" in part:
            hdd += extract_capacity(part)

    return hdd
# HDD

In [41]:
def extract_flash_storage(text):

    parts = [part.strip() for part in text.split("+")]

    flash = 0

    for part in parts:

        if "Flash Storage" in part:
            flash += extract_capacity(part)

    return flash
# Flash Storage

In [ ]:
def extract_hybrid(text):

    parts = [part.strip() for part in text.split("+")]

    hybrid = 0

    for part in parts:

        if "Hybrid" in part:
            hybrid += extract_capacity(part)

    return hybrid
# Hybrid

In [43]:
df["hdd"] = df["memory"].apply(extract_hdd)

df["flash_storage"] = df["memory"].apply(extract_flash_storage)

df["hybrid"] = df["memory"].apply(extract_hybrid)

In [44]:
df[
    [
        "memory",
        "ssd",
        "hdd",
        "flash_storage",
        "hybrid"
    ]
].head(20)

                 memory    ssd     hdd  flash_storage  hybrid
0             128GB SSD  128.0     0.0            0.0     0.0
1   128GB Flash Storage    0.0     0.0          128.0     0.0
2             256GB SSD  256.0     0.0            0.0     0.0
3             512GB SSD  512.0     0.0            0.0     0.0
4             256GB SSD  256.0     0.0            0.0     0.0
5             500GB HDD    0.0   500.0            0.0     0.0
6   256GB Flash Storage    0.0     0.0          256.0     0.0
7   256GB Flash Storage    0.0     0.0          256.0     0.0
8             512GB SSD  512.0     0.0            0.0     0.0
9             256GB SSD  256.0     0.0            0.0     0.0
10            500GB HDD    0.0   500.0            0.0     0.0
11            500GB HDD    0.0   500.0            0.0     0.0
12            256GB SSD  256.0     0.0            0.0     0.0
13            256GB SSD  256.0     0.0            0.0     0.0
14            256GB SSD  256.0     0.0            0.0     0.0
15            256GB SSD  256.0     0.0            0.0     0.0
16            256GB SSD  256.0     0.0            0.0     0.0
17            512GB SSD  512.0     0.0            0.0     0.0
18              1TB HDD    0.0  1024.0            0.0     0.0
19            128GB SSD  128.0     0.0            0.0     0.0

Test

In [ ]:

from src.feature_engineering import (
    extract_capacity,
    extract_ssd,
    extract_hdd,
    extract_flash_storage,
    extract_hybrid
)

In [46]:
extract_ssd("512GB SSD + 512GB SSD")

1024.0

In [47]:
extract_hdd("512GB SSD + 1TB HDD")

1024.0

In [48]:
extract_flash_storage("64GB Flash Storage")

64.0

In [50]:
extract_hybrid("1.0TB Hybrid")

1024.0

In [51]:
df["ssd"] = df["memory"].apply(extract_ssd)

df["hdd"] = df["memory"].apply(extract_hdd)

df["flash_storage"] = df["memory"].apply(extract_flash_storage)

df["hybrid"] = df["memory"].apply(extract_hybrid)

In [52]:
df.head()

,company,product,type_name,inches,screen_resolution,cpu_company,cpu_type,cpu_frequency,ram,memory,gpu_company,gpu_type,operating_system,weight,price,ssd,hdd,flash_storage,hybrid
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69,128.0,0.0,0.0,0.0
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94,0.0,0.0,128.0,0.0
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00,256.0,0.0,0.0,0.0
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45,512.0,0.0,0.0,0.0
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60,256.0,0.0,0.0,0.0

Save new dataset

In [53]:
from pathlib import Path

FEATURED_DATA_PATH = Path("../data/processed/laptop_featured.csv")

df.to_csv(FEATURED_DATA_PATH, index=False)

print("Feature engineered dataset saved successfully.")

Feature engineered dataset saved successfully.

In [54]:
# Test the saved file
df_featured = pd.read_csv("../data/processed/laptop_featured.csv")

df_featured.head()

,company,product,type_name,inches,screen_resolution,cpu_company,cpu_type,cpu_frequency,ram,memory,gpu_company,gpu_type,operating_system,weight,price,ssd,hdd,flash_storage,hybrid
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69,128.0,0.0,0.0,0.0
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94,0.0,0.0,128.0,0.0
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00,256.0,0.0,0.0,0.0
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45,512.0,0.0,0.0,0.0
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60,256.0,0.0,0.0,0.0

# Summary

In this notebook, we performed the first stage of feature engineering.

Completed tasks:

- Extracted SSD capacity
- Extracted HDD capacity
- Extracted Flash Storage capacity
- Extracted Hybrid Storage capacity
- Validated generated features
- Saved the processed dataset

Output:

data/processed/laptop_featured.csv